{% set name = "cwlref-runner" %}
{% set version = "1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/cwlref-runner-{{ version }}.tar.gz
  sha256: a46662940c1e13453c1cb955167ef2223331449c58b026b7f06c905726aad619

build:
  entry_points:
    - cwl-runner=cwltool.main:main
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - cwltool
    - python >=3.6

test:
  imports:
    - cwltool
  commands:
    - cwl-runner --help
  requires:
    - pip

about:
  home: http://www.commonwl.org
  summary: Install the Common Workflow Language reference implementation under the generic name "cwl-runner"
  license: Apache-2.0
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - mr-c
